"""Version inicial para PostgreSQL

Revision ID: 6330cf7b967c
Revises: 
Create Date: 2025-10-21 00:41:10.313096

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6330cf7b967c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('rol', sa.String(length=10), nullable=False),
    sa.Column('especializacion', sa.String(length=200), nullable=True),
    sa.Column('foto', sa.String(length=200), nullable=True),
    sa.Column('edad', sa.Integer(), nullable=True),
    sa.Column('nivel', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('asesoria',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('descripcion', sa.String(length=200), nullable=False),
    sa.Column('costo', sa.Float(), nullable=False),
    sa.Column('max_alumnos', sa.Integer(), nullable=False),
    sa.Column('temas', sa.String(length=200), nullable=False),
    sa.Column('maestro_id', sa.Integer(), nullable=False),
    sa.Column('total_pagado', sa.Float(), nullable=True),
    sa.Column('meet_link', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['maestro_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('asesoria_alumno',
    sa.Column('asesoria_id', sa.Integer(), nullable=False),
    sa.Column('alumno_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['alumno_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['asesoria_id'], ['asesoria.id'], ),
    sa.PrimaryKeyConstraint('asesoria_id', 'alumno_id')
    )
    op.create_table('registro_asesoria',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asesoria_id', sa.Integer(), nullable=False),
    sa.Column('alumno_id', sa.Integer(), nullable=False),
    sa.Column('pagado', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['alumno_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['asesoria_id'], ['asesoria.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('registro_asesoria')
    op.drop_table('asesoria_alumno')
    op.drop_table('asesoria')
    op.drop_table('user')
    # ### end Alembic commands ###
